### ISSUE TITLE
Release version 1.5.0

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#186]
This issue is for tracking changes for the 1.5.0 release.  Target release date: **Thursday, February 27th**.

### Pre-release steps
- [x] Resolve issues in PR #135 and merge
- [x] Complete review of PR #164, resolve issues, and merge
- [x] Complete review of PR #177, resolve issues, and merge
- [x] Complete review of PR #178, resolve issues, and merge
- [x] Complete review of PR #179, resolve issues, and merge (if necessary, this is a candidate to punt and resolve after the release)

### [Release steps](https://github.com/10up/classifai/blob/develop/CONTRIBUTING.md#release-instructions)
- [x] Branch: Starting from `develop`, cut a release branch named `release/1.5.0` for your changes.
- [x] Version bump: Bump the version number in `classifai.php`, `config.php`, `package-lock.json`, `package.json`, and `classifai.pot` if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in `CHANGELOG.md`.
- [x] Translations: Update the `.pot` file by running `npm run makepot`.
- [x] Props: update `CREDITS.md` file with any new contributors, confirm maintainers are accurate
- [x] New files: Check to be sure any new files/paths that are unnecessary in the production version are included in `.github/action-release/rsync-filter.txt`.
- [x] Readme updates: Make any other readme changes as necessary in `CHANGELOG.md` and `README.md`.
- [x] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `master` (`git checkout master && git merge --no-ff develop`). `master` contains the stable development version.
- [x] Push: Push your master branch to GitHub (e.g. `git push origin master`).
- [x] [Wait for build](https://xkcd.com/303/): Head to the [Actions](https://github.com/10up/classifai/actions) tab in the repo and wait for it to finish if it hasn't already. If it doesn't succeed, figure out why and start over.
- [x] Check the build: Check out the `stable` branch and test for functionality locally.
- [x] Release: Create a [new release](https://github.com/10up/classifai/releases/new), naming the tag and the release with the new version number, and targeting the `stable` branch. Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the [1.5.0 milestone](https://github.com/10up/classifai/milestone/6?closed=1).  The release should now appear under [releases](https://github.com/10up/classifai/releases) and in the WordPress admin as an update as well.
- [x] Close milestone: Edit the [1.5.0 milestone](https://github.com/10up/classifai/milestone/6) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description field`), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `1.5.0` do not make it into the release, update their milestone to `1.5.1`, `1.6.0`, `2.0.0` or `Future Release`.

**Comment by jeffpaul** [comment]
Noting here that the release process errored out here: https://github.com/10up/classifai/runs/472927828?check_suite_focus=true.  Which relates to this step in the release process: https://github.com/10up/classifai/blob/f00818a57a417ec3c06cbdc53b0e8f5c0a7d5b54/.github/action-release/entrypoint.sh#L19.  My suspicion is that the https://github.com/10upbot account is no longer in the 10up org or with access to ClassifAI and causing the failure, but I'll review next week when necessary folks are around to chat with.  Apologies for the delay on the release.

**Comment by helen** [comment]
I think this may need a `git fetch origin` before it does the worktree bit, can try it from a branch off master and see if it runs correctly upon merge.

**Comment by ryanwelcher** [comment]
1.5.0 is live https://github.com/10up/classifai/releases/tag/1.5.0
