### ISSUE TITLE
Release version 1.5.1

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#197]
This issue is for tracking changes for the 1.5.0 release.  Target release date: **Friday, March 6th**.

### Pre-release steps
- [x] Complete review of PR #195, resolve issues, and merge
- [x] Complete review of PR #196, resolve issues, and merge
- [x] Complete review of PR #198, resolve issues, and merge

### [Release steps](https://github.com/10up/classifai/blob/develop/CONTRIBUTING.md#release-instructions)
- [x] Branch: Starting from `develop`, cut a release branch named `release/1.5.1` for your changes.
- [x] Version bump: Bump the version number in `classifai.php`, `classifai.pot`, `config.php`, `package-lock.json`, `package.json`, and `readme.txt` if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in `CHANGELOG.md`.
- [x] Translations: Update the `.pot` file by running `npm run makepot`.
- [x] Props: update `CREDITS.md` file with any new contributors, confirm maintainers are accurate
- [ ] New files: Check to be sure any new files/paths that are unnecessary in the production version are included in `.github/action-release/rsync-filter.txt`.
- [x] Readme updates: Make any other readme changes as necessary in `CHANGELOG.md` and `README.md`.
- [x] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `master` (`git checkout master && git merge --no-ff develop`). `master` contains the stable development version.
- [x] Push: Push your master branch to GitHub (e.g. `git push origin master`).
- [x] [Wait for build](https://xkcd.com/303/): Head to the [Actions](https://github.com/10up/classifai/actions) tab in the repo and wait for it to finish if it hasn't already. If it doesn't succeed, figure out why and start over.
- [x] Check the build: Check out the `stable` branch and test for functionality locally.
- [x] Release: Create a [new release](https://github.com/10up/classifai/releases/new), naming the tag and the release with the new version number, and targeting the `stable` branch. Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the [1.5.1 milestone](https://github.com/10up/classifai/milestone/11?closed=1).  The release should now appear under [releases](https://github.com/10up/classifai/releases) and in the WordPress admin as an update as well.
- [x] Close milestone: Edit the [1.5.1 milestone](https://github.com/10up/classifai/milestone/11) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description field`), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `1.5.1` do not make it into the release, update their milestone to `1.5.2`, `1.6.0`, `2.0.0` or `Future Release`.
