### ISSUE TITLE
Release version 1.7.0

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#289]
This issue is for tracking changes for the 1.7.0 release.  Target release date: **August 2021**.

### Pre-release steps
- [x] Complete review of PR #275, resolve issues, and merge
- [x] Complete review of PR #282, resolve issues, and merge
- [x] Complete review of PR #209, resolve issues, and merge
- ~[ ] Complete review of PR #212, resolve issues, and merge~
- ~[ ] Complete review of PR #253, resolve issues, and punt / close / merge~
- [x] Complete review of PR #263, resolve issues, and merge
- ~[ ] Complete review of PR #268, resolve issues, and punt / close / merge~
- ~[ ] Craft PR to handle docs changes on #109, review and merge~
- [x] Test against WP 5.8 and bump `tested-up-to` via #261 
- ~[ ] Craft PR to handle filter addition on #266, review and merge~
- [x] Complete review of PR #290, resolve issues, and merge

### [Release steps](https://github.com/10up/classifai/blob/develop/CONTRIBUTING.md#release-instructions)
- [x] Branch: Starting from `develop`, cut a release branch named `release/1.7.0` for your changes.
- [x] Version bump: Bump the version number in `classifai.php`, `classifai.pot`, `config.php`, `package-lock.json`, `package.json`, and `readme.txt` if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in `CHANGELOG.md`.
- [x] Translations: Update the `.pot` file by running `npm run makepot`.
- [x] Props: update `CREDITS.md` file with any new contributors, confirm maintainers are accurate
- [x] New files: Check to be sure any new files/paths that are unnecessary in the production version are included in `.github/action-release/rsync-filter.txt`.
- [x] Readme updates: Make any other readme changes as necessary in `README.md` and `readme.txt`.
- [x] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `trunk` (`git checkout trunk && git merge --no-ff develop`). `trunk` contains the stable development version.
- [x] Push: Push your trunk branch to GitHub (e.g. `git push origin trunk`).
- [x] [Wait for build](https://xkcd.com/303/): Head to the [Actions](https://github.com/10up/classifai/actions) tab in the repo and wait for it to finish if it hasn't already. If it doesn't succeed, figure out why and start over.
- [x] Check the build: Check out the `stable` branch and test for functionality locally.
- [x] Release: Create a [new release](https://github.com/10up/classifai/releases/new), naming the tag and the release with the new version number, and targeting the `stable` branch. Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the [milestone](https://github.com/10up/classifai/milestone/12?closed=1).  The release should now appear under [releases](https://github.com/10up/classifai/releases) and in the WordPress admin as an update as well.
- [x] Close milestone: Edit the [milestone](https://github.com/10up/classifai/milestone/12) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description field`), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `1.7.0` do not make it into the release, update their milestone to `1.8.0` or `Future Release`.
- [x] Version bump (again): In the `develop` branch (`cd ../ && git checkout develop`) bump the version number in `classifai.php` to `X.Y.(Z+1)-dev`.  It's okay if the next release might be a different version number; that change can be handled right before release in the first step, as might also be the case with `@since` annotations.

**Comment by jeffpaul** [comment]
Tagging @helen to pick up with final review on #282, then continuing with the release steps here utilizing #303.
