### ISSUE TITLE
Content Authenticity / Credentials / Provenance tracking issue

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#652]
### Is your enhancement related to a problem? Please describe.

One issue with AI-generated (or augmented) content is that its currently hard for a consumer of that content to know that it was AI generated or not by merely reading/viewing said content.  Said more simply, without taking some actions here we're potentially contributing to the erosion of trust in online content and interactions.  We have the opportunity with ClassifAI to help (1) track what content is generated or augmented via AI and (2) provide mechanisms to alert users on the front-end when viewing said content.  While we cannot prevent deepfakes and similar malevolent actors, it feels like we can still try and help contribute as best we can to improve the trust in content and interactions online.

### Designs

As originally referenced in https://github.com/10up/classifai/issues/398#issuecomment-1563388653, we can look to provide a way to track what content has been generated or augmented with AI and then display attribution where that data exists.  While we have an image generation credit and license in the caption of generated images we could go further with the following:
- [ ] Leverage [Content Authenticity Initiative (CAI)](https://opensource.contentauthenticity.org/) tooling to integrate secure provenance signals (aka C2PA data) into image files generated/augment via AI (currently the [Node.js option](https://opensource.contentauthenticity.org/docs/c2pa-node/) might be the most feasible) _noting this could be iterated upon to also include image editing done within the Media Library_
- [ ] Displaying C2PA data via a [Content Credentials `cr` overlay](https://contentcredentials.org/) on the front-end for images (where said data exists)
- [ ] Expose the C2PA data when viewing images in the Media Library, potentially having that similarly available as a new collapsed-by-default sidebar panel in the image/cover image/etc blocks

While the CAI tooling does not yet appear to support similar tracking and attribution for text-based content, we could still look to add some custom ClassifAI meta to posts where AI tooling is used to track what was done, when, and by which users so that data could be presented or utilize later on (e.g. post footnotes referencing AI features used in the generation of the post content, reporting on what features are most used).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
OpenAI just announced that any images generated using DALL·E 3 will now have C2PA metadata associated with them: https://help.openai.com/en/articles/8912793-c2pa-in-dall-e-3. We haven't updated to DALL·E 3 yet but that is on the near-term roadmap

**Comment by jeffpaul** [comment]
Lol I just came here to share the same thing, @dkotter 🥇 @jeffpaul 🥈 
https://twitter.com/OpenAI/status/1754930271970005161
> Images generated in ChatGPT and our API now include metadata using C2PA specifications.
>
> This allows anyone (including social platforms and content distributors) to see that an image was generated by our products. [https://help.openai.com/en/articles/8912793-c2pa-in-dall-e-3](https://t.co/kRv3mFnQFI)
>
> ![image](https://github.com/10up/classifai/assets/2818133/26c4771d-5ea8-4f8d-a4f1-8c8fb22a1b8b)

**Comment by jeffpaul** [comment]
*ahem* https://opensource.contentauthenticity.org/docs/c2pa-js/ *ahem*
